services:
  db:
    image: mysql:8.4
    container_name: ru_ufpe_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ru_ufpe
      MYSQL_USER: ru_user
      MYSQL_PASSWORD: ru_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot_pass"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
